sonar.projectKey=OwnLift-Server
sonar.host.url=http://localhost:9000
sonar.analysisCache.enabled=false
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*.test.ts
sonar.exclusions=node_modules/**,dist/**,coverage/**,public/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
